api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "ikarus-bundle-transform"
type = "function"
uid = "f9d7d649-34ba-23e1-53f6-435b66d0eac981059f0b"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
