api_version = "2025-07"
uid = "c931b201-436d-33fe-d85c-1b442e888e7262183305"

[[extensions]]
name = "IkarusDelta Bundles"
handle = "ikarus-order-summary"
type = "ui_extension"

  [[extensions.targeting]]
  target = "admin.order-details.block.render"
  module = "./src/BlockExtension.jsx"
