api_version = "2025-07"

[[extensions]]
name = "IkarusDelta Bundles"
handle = "ikarus-order-summary"
type = "ui_extension"

  [[extensions.targeting]]
  target = "admin.order-details.block.render"
  module = "./src/BlockExtension.jsx"
